import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/provider/theme-provider'
import { cn } from '@/lib/utils'
import AuthProvider from '@/lib/session-provider'
import { Toaster } from 'sonner'
import { SocketProvider } from '@/components/provider/socket-provider'
import { QueryProvider } from '@/components/provider/query-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        inter.className,
        'bg-white dark:bg-neutral-800'
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
          storageKey="discord-theme"
        >
          <SocketProvider>
            <AuthProvider>
              <QueryProvider>
                {children}
              </QueryProvider>
              <Toaster position='top-center' />
            </AuthProvider>
          </SocketProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
