import type { Metadata } from 'next'
import '@/app/globals.css'
import { SideBar, SideBarSkeleton } from '@/components/globals/sidebar'
import { Suspense } from 'react'
import { fetchUser } from '@/lib/auth-service'
import { redirect } from 'next/navigation'
import { db } from '@/lib/db'


export const metadata: Metadata = {
  title: 'Servers | Discord',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children, params
}: {
  children: React.ReactNode,
  params: { serverId: string }
}) {

  const res = await fetchUser();
  if (!res || !res.success || !res.user) redirect('/')

  const data = await db.server.findFirst({
    where: {
      id: params.serverId,
      members: {
        some: {
          userId: res.user.id
        }
      }
    }
  })
  if (!data) redirect('/')

  return (
    <main className='flex custom-height overflow-hidden'>
      <Suspense fallback={<SideBarSkeleton />}>
        <SideBar user={res.user} />
      </Suspense>
      {children}
    </main>
  )
}
