import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import { ThemeProvider } from '@/components/provider/theme-provider'
import { cn } from '@/lib/utils'
import AuthProvider from '@/lib/session-provider'
import { Toaster } from 'sonner'
import { SocketProvider } from '@/components/provider/socket-provider'
import { QueryProvider } from '@/components/provider/query-provider'
import { fetchUser } from '@/lib/auth-service'
import { redirect } from 'next/navigation'
import { Suspense } from 'react'
import { SideBar, SideBarSkeleton } from '@/components/globals/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  const res = await fetchUser();
  if (!res || !res.success || !res.user) redirect('/')

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        inter.className,
        'bg-white dark:bg-neutral-800'
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
          storageKey="discord-theme"
        >
          <SocketProvider>
            <AuthProvider>
              <QueryProvider>
                <main className='flex custom-height overflow-hidden'>
                  <Suspense fallback={<SideBarSkeleton />}>
                    <SideBar user={res.user} />
                  </Suspense>
                  {children}
                </main>
              </QueryProvider>
              <Toaster position='top-center' />
            </AuthProvider>
          </SocketProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

